@ECHO OFF
SET CONTADOR=0
FOR %%I IN (%*) DO (
	SET /A CONTADOR += 1
)
IF %CONTADOR% NEQ 2 (
	ECHO PARAMETROS INCORRECTOS
	EXIT /B
)
IF "%1" == "%2" (
	ECHO PARAMETROS IGUALES
) ELSE (
	ECHO PARAMETROS DISTINTOS
)