DROP TABLE CRITERIOS CASCADE CONSTRAINTS;
DROP TABLE RESULTADOAPRENDIZAJE CASCADE CONSTRAINTS;
DROP TABLE BLOQUECONTBASICO CASCADE CONSTRAINTS;
DROP TABLE ORIENTADOS CASCADE CONSTRAINTS;
DROP TABLE DEPENDIENTES CASCADE CONSTRAINTS;
DROP TABLE CURSADOS CASCADE CONSTRAINTS;
DROP TABLE ADQUIRIDOS CASCADE CONSTRAINTS;
DROP TABLE OBTENIDOS_MEDIANTE CASCADE CONSTRAINTS;
DROP TABLE COMPETENCIAS CASCADE CONSTRAINTS;
DROP TABLE OBJETIVOS_GENERALES CASCADE CONSTRAINTS;
DROP TABLE TITULOS CASCADE CONSTRAINTS;
DROP TABLE MODULOS CASCADE CONSTRAINTS;
DROP TABLE FAMILIAS_PROFESIONALES CASCADE CONSTRAINTS;
CREATE TABLE FAMILIAS_PROFESIONALES(
	NOMBRE		VARCHAR2(50) NOT NULL,
	DESCRIPCION VARCHAR2(300) NOT NULL,
	CONSTRAINT PK_FAMILIAS_PROFESIONALES PRIMARY KEY (NOMBRE)
);
CREATE TABLE MODULOS(
	CODIGO		VARCHAR2(4) NOT NULL,
	NOMBRE		VARCHAR2(40),
	HORAS_ANUALES	NUMBER(3) NOT NULL,
	HORAS_SEMANALES	NUMBER(2) NOT NULL,
	CURSO		 	NUMBER(1,2) NOT NULL,
	CONSTRAINT PK_MODULOS PRIMARY KEY(CODIGO),
	CONSTRAINT CK_MODULOS_HANUAL CHECK(HORAS_ANUALES >0),
	CONSTRAINT CK_MODULOS_HSEMANAL CHECK(HORAS_SEMANALES >0),
	CONSTRAINT CK_MODULOS_CURSO CHECK (CURSO IN (1,2))
);
CREATE TABLE TITULOS(
	NOMBRE	 			VARCHAR2(65) NOT NULL,
	DURACION			NUMBER(4)	NOT NULL,
	DENOMINACION		VARCHAR2(50) NOT NULL,
	COMPETENCIA_GENERAL	VARCHAR2(500) NOT NULL,	
	NOMBRE_FAMILIA 		VARCHAR2(50) NOT NULL,
	CONSTRAINT PK_TITULOS PRIMARY KEY (NOMBRE),
	CONSTRAINT FK_TITULOS_FAMILIA_PROFES FOREIGN KEY (NOMBRE_FAMILIA)
		REFERENCES FAMILIAS_PROFESIONALES,
	CONSTRAINT CK_TITULOS_DURACIONMENORIGUAL CHECK (DURACION <= 2000)
);
CREATE TABLE OBJETIVOS_GENERALES(
	CODIGO			CHAR(1) NOT NULL,
	NOMBRE_TITULO	VARCHAR2(65) NOT NULL,
	DESCRIPCION		VARCHAR2(300) NOT NULL,
	CONSTRAINT PK_OBJETIVOS_GENERALES PRIMARY KEY (CODIGO),
	CONSTRAINT FK_OBJETIVOS_GEN_TITULOS FOREIGN KEY (NOMBRE_TITULO)
		REFERENCES TITULOS
);
CREATE TABLE COMPETENCIAS(
	CODIGO			CHAR(1) NOT NULL,
	NOMBRE_TITULO	VARCHAR2(65) NOT NULL,
	DESCRIPCION		VARCHAR2(300) NOT NULL,
	CONSTRAINT PK_COMPETENCIAS PRIMARY KEY(CODIGO),
	CONSTRAINT FK_COMPETENCIAS_NOMTIT	FOREIGN KEY(NOMBRE_TITULO)
		REFERENCES TITULOS
);
CREATE TABLE OBTENIDOS_MEDIANTE(
	CODIGO_OBJETIVO		CHAR(1) NOT NULL,
	CODIGO_MODULO		VARCHAR2(4) NOT NULL,
	CONSTRAINT PK_OBTENIDOS_MEDIANTE PRIMARY KEY(CODIGO_OBJETIVO,CODIGO_MODULO),
	CONSTRAINT FK_OBTENIDOS_MEDIANTE_OBJMOD FOREIGN KEY(CODIGO_OBJETIVO)
		REFERENCES OBJETIVOS_GENERALES,
	CONSTRAINT FK_OBTENIDOS_MENDIANTE_MODULO FOREIGN KEY(CODIGO_MODULO)
		REFERENCES MODULOS
);
CREATE TABLE ADQUIRIDOS(
	CODIGO_COMPETENCIA 	CHAR(1) NOT NULL,
	CODIGO_MODULO		VARCHAR2(4) NOT NULL,
	CONSTRAINT PK_ADQUIRIDOS PRIMARY KEY(CODIGO_COMPETENCIA,CODIGO_MODULO),
	CONSTRAINT FK_ADQUIRIDOS_CODCOMP FOREIGN KEY(CODIGO_COMPETENCIA)
		REFERENCES COMPETENCIAS,
	CONSTRAINT FK_ADQUIRIDOS_CODMOD FOREIGN KEY(CODIGO_MODULO)
		REFERENCES MODULOS
);
CREATE TABLE CURSADOS(
	NOMBRE_TITULO		VARCHAR2(65) NOT NULL,
	CODIGO_MODULO		VARCHAR2(4) NOT NULL,
	CONSTRAINT PK_CURSADOS PRIMARY KEY(NOMBRE_TITULO,CODIGO_MODULO),
	CONSTRAINT FK_CURSADOS_NTITULO FOREIGN KEY(NOMBRE_TITULO)
		REFERENCES TITULOS,
	CONSTRAINT FK_CURSADOS_CODMOD FOREIGN KEY(CODIGO_MODULO)
		REFERENCES MODULOS
);

CREATE TABLE DEPENDIENTES(
	CODIGO_MODULO1		VARCHAR2(4) NOT NULL,
	CODIGO_MODULO2		VARCHAR2(4) NOT NULL,
	CONSTRAINT PK_DEPENDIENTES PRIMARY KEY(CODIGO_MODULO1,CODIGO_MODULO2),
	CONSTRAINT FK_DEPENDIENTES_CODMOD1 FOREIGN KEY(CODIGO_MODULO1)
		REFERENCES MODULOS,
	CONSTRAINT FK_DEPENDIENTES_CODMOD2 FOREIGN KEY(CODIGO_MODULO2)
		REFERENCES MODULOS
);
CREATE TABLE ORIENTADOS(
	NOMBRE_TITULO		VARCHAR2(65) NOT NULL,	
	CODIGO_MODULO		VARCHAR2(4) NOT NULL,
	CONSTRAINT PK_ORIENTADOS PRIMARY KEY(NOMBRE_TITULO,CODIGO_MODULO),
	CONSTRAINT FK_ORIENTADOS FOREIGN KEY(NOMBRE_TITULO)
		REFERENCES TITULOS,
	CONSTRAINT FK_ORIENTADOS_CODMOD FOREIGN KEY(CODIGO_MODULO)
		REFERENCES MODULOS
);
CREATE TABLE BLOQUECONTBASICO(
	ID				CHAR(2) NOT NULL,
	NOMBRE			VARCHAR2(250) NOT NULL,
	CODIGO_MODULO	VARCHAR2(4) NOT NULL,
	CONSTRAINT PK_BLOQUECONTBASICO PRIMARY KEY(ID,NOMBRE,CODIGO_MODULO),
	CONSTRAINT FK_BLOQUECONTBASICO_CODMOD FOREIGN KEY(CODIGO_MODULO)
		REFERENCES MODULOS
);
CREATE TABLE RESULTADOAPRENDIZAJE(
	CODIGO			CHAR(1) NOT NULL,
	NOMBRE			VARCHAR2(300) NOT NULL,
	CODIGO_MODULO	VARCHAR2(4) NOT NULL,
	CONSTRAINT PK_RESULTADOAPRENDIZAJE PRIMARY KEY(CODIGO,CODIGO_MODULO),
	CONSTRAINT FK_RESULTADOAPRENDIZAJE_CODMOD FOREIGN KEY(CODIGO_MODULO)
		REFERENCES MODULOS
);
CREATE TABLE CRITERIOS(
	CODIGO							CHAR(1) NOT NULL,
	NOMBRE							VARCHAR2(150) NOT NULL,
	CODIGO_RESULTADO_APRENDIZAJE	CHAR(1) NOT NULL,
	CODIGO_MODULO					VARCHAR2(4) NOT NULL,
	CONSTRAINT PK_CRITERIOS PRIMARY KEY(CODIGO),
	CONSTRAINT FK_CRITERIOS_CODRA FOREIGN KEY(CODIGO_RESULTADO_APRENDIZAJE,CODIGO_MODULO)
	REFERENCES RESULTADOAPRENDIZAJE,	
);