DROP TABLE INGRESOS;
DROP TABLE DESCUENTOS;
DROP TABLE NOMINAS;
DROP TABLE TRABAJA;
DROP TABLE SEDES;
DROP TABLE EMPLEADOS;
DROP TABLE CCC;
DROP TABLE DEPARTAMENTOS;
DROP TABLE CONCEPTOS_RETRIBUTIVOS;
CREATE TABLE CONCEPTOS_RETRIBUTIVOS(
	COD 			NUMBER(2),
	DESCRIPCION 	VARCHAR2(25) NOT NULL,
	CONSTRAINT PK_CONCEPTOS_RETRIBUTIVOS PRIMARY KEY(COD)
	);
CREATE TABLE DEPARTAMENTOS(
	COD 	CHAR(2),
	NOMBRE	VARCHAR2(20) NOT NULL,
	CONSTRAINT PK_DEPARTAMENTOS PRIMARY KEY (COD)
	);
CREATE TABLE CCC(
	ID			CHAR(20),
	IBAN 		CHAR(24) NOT NULL,
	CODBANCO	CHAR(4) NOT NULL,
	CODSUCURSAL	CHAR(4) NOT NULL,
	DC			CHAR(2) NOT NULL,
	NUMCUENTA	CHAR(10) NOT NULL,
	CONSTRAINT PK_CCC PRIMARY KEY (ID)
	);
CREATE TABLE EMPLEADOS(
	NIF 			CHAR(9),
	NOMBRE 			VARCHAR2(20) NOT NULL,
	APELLIDOS 		VARCHAR2(30) NOT NULL,
	ESTADOCIVIL 	CHAR(1) NOT NULL,
	FECHAALTA		DATE NOT NULL,
	NUMHIJOS		NUMBER(2) NOT NULL,
	RETENCION		CHAR(3) NOT NULL,
	IDCUENTA		CHAR(20) NOT NULL,
	CONSTRAINT PK_EMPLEADOS PRIMARY KEY (NIF),
	CONSTRAINT FK_EMPLEADOS_CCC	FOREIGN KEY (IDCUENTA)
		REFERENCES CCC ON DELETE CASCADE
	);
CREATE TABLE SEDES(
	COD				CHAR(2),
	NOMBRE			VARCHAR(15) NOT NULL,
	DEPARTAMENTO	CHAR(2) NOT NULL,
	CONSTRAINT PK_SEDES PRIMARY KEY (COD),
	CONSTRAINT FK_SEDES_DEPARTAMENTOS FOREIGN KEY (DEPARTAMENTO)
		REFERENCES DEPARTAMENTOS ON DELETE CASCADE
	);
CREATE TABLE TRABAJA(
	EMPLEADO			CHAR(9) NOT NULL,
	DEPARTAMENTO 		CHAR(2) NOT NULL,
	FUNCION				VARCHAR(11),
	CONSTRAINT PK_TRABAJA	PRIMARY KEY (EMPLEADO,DEPARTAMENTO),
	CONSTRAINT FK_TRABAJA_EMPLEADOS FOREIGN KEY (EMPLEADO)
		REFERENCES EMPLEADOS,
	CONSTRAINT FK_TRABAJA_DEPARTAMENTOS FOREIGN KEY (DEPARTAMENTO)
		REFERENCES DEPARTAMENTOS
	);
CREATE TABLE NOMINAS(
	EMPLEADO		CHAR(9) NOT NULL,
	EJERCICIOFISCAL	NUMBER(4) NOT NULL,
	MES				NUMBER(2) NOT NULL,
	IMPORTETOTAL	NUMBER (7,2) NOT NULL,
	CONSTRAINT PK_NOMINAS PRIMARY KEY (EMPLEADO,EJERCICIOFISCAL,MES),
	CONSTRAINT FK_NOMINAS_EMPLEADOS FOREIGN KEY (EMPLEADO)
		REFERENCES EMPLEADOS ON DELETE CASCADE
	);
CREATE TABLE DESCUENTOS(
	EMPLEADO		CHAR(9) NOT NULL,
	EJERCICIO		NUMBER(4) NOT NULL,
	MES				NUMBER(2) NOT NULL,
	NUMLINEA		NUMBER(2),
	CANTIDAD		NUMBER(6,2),
	BASE			NUMBER(7,2),
	PORCENTAJE		CHAR(1),
	CONSTRAINT PK_DESCUENTOS PRIMARY KEY (EMPLEADO,EJERCICIO,MES,NUMLINEA),
	CONSTRAINT FK_DESCUENTOS_NOMINAS FOREIGN KEY (EMPLEADO,EJERCICIO,MES)
		REFERENCES NOMINAS ON DELETE CASCADE
	);
CREATE TABLE INGRESOS(
	EMPLEADO		CHAR(9),
	EJERCICIO		NUMBER(4),
	MES				NUMBER(2),
	NUMLINEA		NUMBER(2),
	CANTIDAD		NUMBER(6,2),
	CONCEPTO		NUMBER(2),
	CONSTRAINT PK_INGRESOS PRIMARY KEY (EMPLEADO,EJERCICIO,MES),
	CONSTRAINT FK_INGRESOS_NOMINAS FOREIGN KEY (EMPLEADO,EJERCICIO,MES)
		REFERENCES NOMINAS ON DELETE CASCADE
	CONSTRAINT FK_INGRESOS_CONCEPTOS_RETRIBUTIVOS FOREIGN KEY (CONCEPTO)
		REFERENCES CONCEPTOS_RETRIBUTIVOS ON DELETE CASCADE
	);