CREATE TABLE TIPOSANUNCIOS (
	NOMBRE	VARCHAR2 (25) NOT NULL, 
	CODIGO	VARCHAR2 (1),
	CONSTRAINT PK_TIPOSANUNCIOS PRIMARY KEY (CODIGO)
);
CREATE TABLE CLIENTES (
	DNI NUMBER(9),
	DIRECCION	VARCHAR2 (30) NOT NULL,
	POBLACION	VARCHAR2 (20) NOT NULL,
	PROVINCIA	VARCHAR2 (20) NOT NULL,
	CODIGO_POSTAL	VARCHAR2 (5) NOT NULL,
	EMAIL	VARCHAR2 (30) NOT NULL,
	CONSTRAINT PK_CLIENTES PRIMARY KEY (DNI)
);
CREATE TABLE WEBS (
	URL	VARCHAR2 (35) NOT NULL,
	NOMBRE  VARCHAR2(30) NOT NULL,
	TOPICO	VARCHAR (1) NOT NULL,
	CONSTRAINT PK_WEBS PRIMARY KEY (URL)
);
CREATE TABLE ANUNCIOS (
	CODIGO NUMBER (5),
	NOMBRE VARCHAR2(20) NOT NULL,
	TITULO VARCHAR2 (30) NOT NULL,
	CONTENIDO  VARCHAR2(20) NOT NULL,
	CATEGORIA VARCHAR (1) NOT NULL,
	PRECIO	NUMBER (4,2) NOT NULL,
	CODIGO_TIPOSANUNCIOS	VARCHAR2 (1),
	DNI_CLIENTES NUMBER (9),
	CONSTRAINT PK_ANUNCIOS PRIMARY KEY (CODIGO),
	CONSTRAINT FK_ANUNCIOS_TIPOSANUNCIOS FOREIGN KEY (CODIGO_TIPOSANUNCIOS)
		REFERENCES TIPOSANUNCIOS,
	CONSTRAINT FK_ANUNCIOS_CLIENTES	FOREIGN KEY (DNI_CLIENTES)
		REFERENCES CLIENTES
);
CREATE TABLE APARECE (
	FECH_INICIO	DATE,
	FECH_FIN 	DATE,
	URL_WEBS	VARCHAR2 (35),
	CODIGO_ANUNCIOS	NUMBER (5),                                                                                                                                                                   
	CONSTRAINT PK_APARECE PRIMARY KEY (FECH_INICIO,URL_WEBS,CODIGO_ANUNCIOS),
	CONSTRAINT FK_APARECE_WEBS FOREIGN KEY (URL_WEBS)
		REFERENCES WEBS,
	CONSTRAINT FK_APARECE_ANUNCIOS FOREIGN KEY (CODIGO_ANUNCIOS)
		REFERENCES ANUNCIOS
);