CREATE TABLESPACE RACE
	DATAFILE `DF_RACE.ORA` SIZE 10M;
CREATE TABLESPACE TEMPRACE
	DATAFILE ‘DF_TEMPRACE’ SIZE 10M;

CREATE USER EQUIPO6
	IDENTIFIED BY EQUIPO6
	DEFAULT TABLESPACE RACE
	TEMPORARY TABLESPACE TEMPRACE
	QUOTA UNLIMITED ON RACE;

CREATE USER MEJIASFRAN
	IDENTIFIED BY  MEJIASFRAN
	DEFAULT  TABLESPACE RACE
	TEMPORARY TABLESPACE TEMPRACE
	QUOTA UNLIMITED ON RACE;

GRANT CONNECT, RESOURCE TO EQUIPO6;

GRANT CONNECT, RESOURCE TO MEJIASFRAN;

REVOKE UNLIMITED TABLESPACE FROM EQUIPO6;
REVOKE UNLIMITED TABLESPACE FROM MEJIASFRAN;