@ECHO OFF
SET DIRECTORIO=C:\ACTIND8
IF EXIST "%DIRECTORIO%\" (
	ECHO EL DIRECTORIO ACTIND8 EXISTE...
	ECHO BORRANDO DIRECTORIO ACTIND8...
	RMDIR /S /Q ACTIND8
	ECHO CREANDO DIRECTORIO ACTIND8...
	MKDIR %DIRECTORIO%
	CD %DIRECTORIO%
	MKDIR EJER1 EJER2 EJER3
	COPY C:\USERS\%USERNAME%\DESKTOP\CUANTOS.bat %DIRECTORIO%\EJER1
	ECHO RENOMBRANDO EJERCICIO 1
	RENAME %DIRECTORIO%\EJER1\CUANTOS.bat EJE1.bat
	COPY C:\USERS\%USERNAME%\DESKTOP\CAMBIO.bat %DIRECTORIO%\EJER2
	ECHO RENOMBRANDO EJERCICIO 2
	RENAME %DIRECTORIO%\EJER2\CUANTOS.bat EJE2.bat
	COPY C:\USERS\%USERNAME%\DESKTOP\IGUAL.bat %DIRECTORIO%\EJER3
	ECHO RENOMBRANDO EJERCICIO 3
	RENAME %DIRECTORIO%\EJER3\CUANTOS.bat EJE3.bat
) ELSE (
	ECHO EL DIRECTORIO ACTIND8 NO EXISTE...
	ECHO CREANDO DIRECTORIO ACTIND8...
	MKDIR %DIRECTORIO%
	CD %DIRECTORIO%
	MKDIR EJER1 EJER2 EJER3
	COPY C:\USERS\%USERNAME%\DESKTOP\CUANTOS.bat %DIRECTORIO%\EJER1
	ECHO RENOMBRANDO EJERCICIO 1
	RENAME %DIRECTORIO%\EJER1\CUANTOS.bat EJE1.bat
	COPY C:\USERS\%USERNAME%\DESKTOP\CAMBIO.bat %DIRECTORIO%\EJER2
	ECHO RENOMBRANDO EJERCICIO 2
	RENAME %DIRECTORIO%\EJER2\CAMBIO.bat EJE2.bat
	COPY C:\USERS\%USERNAME%\DESKTOP\IGUAL.bat %DIRECTORIO%\EJER3
	ECHO RENOMBRANDO EJERCICIO 3
	RENAME %DIRECTORIO%\EJER3\IGUAL.bat EJE3.bat
)