@ECHO OFF
SET CONTADOR=0
FOR %%I IN (%*) DO (
	SET /A CONTADOR += 1
)
IF %CONTADOR% NEQ 2 (
	ECHO PARAMETROS INCORRECTOS
	EXIT /B
)
IF NOT EXIST %1 (
	ECHO EL ARCHIVO %1 NO EXSISTE
) ELSE (
IF NOT EXIST %2 (
	ECHO RENOMBRANDO ARCHIVO %1
	RENAME %1 %2
	ECHO ARCHIVO RENOMBRADO A %2
) ELSE (
	ECHO EL ARCHIVO %2 YA EXISTE
)
)
