DROP TABLE VENTAS CASCADE CONSTRAINTS;
DROP TABLE PEDIDOS CASCADE CONSTRAINTS;
DROP TABLE ARTICULOS CASCADE CONSTRAINTS;
DROP TABLE FABRICANTES CASCADE CONSTRAINTS;
DROP TABLE TIENDAS CASCADE CONSTRAINTS;
CREATE TABLE TIENDAS(
	NIF			VARCHAR2(10) NOT NULL,
	NOMBRE		VARCHAR2(20),
	DIRECCION	VARCHAR2(20),
	POBLACION	VARCHAR2(20),
	PROVINCIA	VARCHAR2(20),
	CODPOSTAL	NUMBER(5),
	CONSTRAINT PK_TIENDAS PRIMARY KEY(NIF),
	CONSTRAINT CK_TIENDAS_PROVINCIAMAYUSC CHECK(PROVINCIA = UPPER(PROVINCIA))
	);
CREATE TABLE FABRICANTES(
	COD_FABRICANTE	NUMBER(3) NOT NULL,
	NOMBRE			VARCHAR2(15),
	PAIS			VARCHAR2(15),
	CONSTRAINT PK_FABRICANTES PRIMARY KEY(COD_FABRICANTE),
	CONSTRAINT CK_FABRICANTES_NOMBREMAYUS CHECK (NOMBRE=UPPER(NOMBRE)),
	CONSTRAINT CK_FABRICANTES_PAISMAYUS CHECK (PAIS=UPPER(PAIS))
	);
CREATE TABLE ARTICULOS(
	ARTICULO			VARCHAR2(20) NOT NULL,
	COD_FABRICANTE		NUMBER(3) NOT NULL,
	PESO				NUMBER(3) NOT NULL,
	CATEGORIA			VARCHAR2(10) NOT NULL,
	PRECIO_VENTA		NUMBER(4),
	PRECIO_COSTO		NUMBER(4),
	EXISTENCIAS			NUMBER(5),
	CONSTRAINT PK_ARTICULOS PRIMARY KEY(ARTICULO,COD_FABRICANTE,PESO,CATEGORIA),
	CONSTRAINT FK_ARTICULOS_FABRICANTES FOREIGN KEY(COD_FABRICANTE)
		REFERENCES FABRICANTES,
	CONSTRAINT CK_ARTICULOS_PCOSTOMAYCERO CHECK(PRECIO_COSTO >0),
	CONSTRAINT CK_ARTICULOS_PESO CHECK(PESO >0),
	CONSTRAINT CK_ARTICULOS_CATEG CHECK(CATEGORIA IN('Primera','Segunda','Tercera'))
	);
CREATE TABLE PEDIDOS(
	NIF				 VARCHAR2(10) NOT NULL,
	ARTICULO		 VARCHAR2(20) NOT NULL,
	COD_FABRICANTE	 NUMBER(3) NOT NULL,
	PESO			 NUMBER(3) NOT NULL,
	CATEGORIA		 VARCHAR2(10) NOT NULL,
	FECHA_PEDIDO	 DATE NOT NULL,
	UNIDADES_PEDIDAS NUMBER(4),
	CONSTRAINT PK_PEDIDOS PRIMARY KEY(NIF,ARTICULO,COD_FABRICANTE,PESO,CATEGORIA,FECHA_PEDIDO),
	CONSTRAINT FK_PEDIDOS_FABRICANTES FOREIGN KEY(COD_FABRICANTE)
		REFERENCES FABRICANTES,
	CONSTRAINT CK_PEDIDOS_UDPEDMAYCERO CHECK(UNIDADES_PEDIDAS >0),
	CONSTRAINT CK_PEDIDOS_CATEGOR CHECK(CATEGORIA IN('Primera','Segunda','Tercera')),
	CONSTRAINT FK_PEDIDOS_PEARTICULOS FOREIGN KEY(ARTICULO,COD_FABRICANTE,PESO,CATEGORIA)
		REFERENCES ARTICULOS ON DELETE CASCADE,
	CONSTRAINT FK_PEDIDOS_PNIF FOREIGN KEY(NIF)
		REFERENCES TIENDAS
	);
CREATE TABLE VENTAS(
	NIF					VARCHAR2(10) NOT NULL,
	ARTICULO			VARCHAR2(20) NOT NULL,
	COD_FABRICANTE		NUMBER(3) NOT NULL,
	PESO				NUMBER(3) NOT NULL,
	CATEGORIA			VARCHAR2(10) NOT NULL,
	FECHA_VENTA			DATE NOT NULL,
	UNIDADES_VENDIDAS	NUMBER(4),
	CONSTRAINT PK_VENTAS PRIMARY KEY(NIF,ARTICULO,COD_FABRICANTE,PESO,CATEGORIA,FECHA_VENTA),
	CONSTRAINT FK_VENTAS_CODFABRICANTE FOREIGN KEY(COD_FABRICANTE)
		REFERENCES FABRICANTES,
	CONSTRAINT CK_VENTAS_UDVENDMAYCERO CHECK(UNIDADES_VENDIDAS >0),
	CONSTRAINT CK_VENTAS_CATEGORIA CHECK(CATEGORIA IN('Primera','Segunda','Tercera')),
	CONSTRAINT FK_PEDIDOS_ARTICULOS FOREIGN KEY(ARTICULO,COD_FABRICANTE,PESO,CATEGORIA)
		REFERENCES ARTICULOS ON DELETE CASCADE,
	CONSTRAINT FK_PEDIDOS_NIF FOREIGN KEY(NIF)
		REFERENCES TIENDAS
	);
	
	ALTER TABLE TIENDAS ADD CONSTRAINT CK_TIENDAS_NOMBRETITULO CHECK(NOMBRE=INITCAP(NOMBRE));
	DESC TIENDAS;
	ALTER TABLE PEDIDOS MODIFY UNIDADES_PEDIDAS NUMBER(6);
	ALTER TABLE VENTAS MODIFY UNIDADES_VENDIDAS NUMBER(6);
	ALTER TABLE TIENDAS ADD CONSTRAINT CK_TIENDAS_NOTOLEDO CHECK (UPPER(PROVINCIA) !='TOLEDO');
	ALTER TABLE PEDIDOS ADD PVP NUMBER(3,2);
	ALTER TABLE VENTAS ADD PVP NUMBER(3,2);